server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://35.194.160.86:8761/eureka,http://35.194.160.86:8762/eureka,http://35.194.160.86:8763/eureka
    instance:
      hostname: home1
spring:
  application:
    name: client