eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka,http://localhost:8672/eureka,http://localhost:8673/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka1
